version: '3.8'

services:
  web:
    build: ./
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/api
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=api
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
